name: Run Mobile Tests (Redmi Only)

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted

    steps:
      # ✅ 1. Checkout PUBLIC repo (testcases)
      - name: Checkout Public Repo
        uses: actions/checkout@v4

      # ✅ 2. Checkout PRIVATE repo (core framework)
      - name: Checkout Private Core Repo
        uses: actions/checkout@v4
        with:
          repository: anilds47/qa-core-framework
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          path: core-framework

      # ✅ 3. Build core framework
      - name: Build Core Framework
        run: |
          cd core-framework
          mvn clean install -DskipTests

      # ✅ 4. Set Redmi Device Config
      - name: Set Device
        run: |
          echo "UDID=a443a697" >> $GITHUB_ENV
          echo "DEVICE_NAME=Redmi Note 10 Pro" >> $GITHUB_ENV
          echo "PLATFORM_VERSION=13" >> $GITHUB_ENV

      # ✅ 5. Run Tests on Redmi Device
      - name: Run on Redmi Device
        run: |
          adb devices

          mvn clean test \
          -Dtarget=real \
          -Dudid=$UDID \
          -DdeviceName="$DEVICE_NAME" \
          -DplatformVersion=$PLATFORM_VERSION